routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\PortfolioController;
use App\Http\Controllers\Admin\ServicesController;
use App\Http\Controllers\Admin\TeamController;
use App\Http\Controllers\Admin\ProjectsController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\EditProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){

        Route::get('/', [\App\Http\Controllers\IndexController::class, 'index'])->name('index');
        Route::get('/teams', [\App\Http\Controllers\TeamController::class, 'team'])->name('client.team.index');
        Route::get('/abouts', [\App\Http\Controllers\AboutUsController::class, 'about'])->name('client.about-us.index');
        Route::get('/portfolio', [\App\Http\Controllers\PortfoliosController::class, 'portfolio'])->name('client.portfolio.index');
        Route::get('/service', [\App\Http\Controllers\ServiceController::class, 'service'])->name('client.service.index');
        Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->where('name', '[A-Za-z]+');
        Route::get('/project', [App\Http\Controllers\ProjectController::class, 'project'])->name('client.projects.index');
        Route::get('/contact', [App\Http\Controllers\ContactController::class, 'contact'])->name('client.contact.index')->where('name', '[A-Za-z]+');
        Route::get('/mail', [App\Http\Controllers\MailController::class, 'sendEmail'])->name('emails.mail');

});

Route::middleware(['auth:web'])->group(function () {

    Route::group(['prefix' => 'admin'], function () {

        Route::resources([
            'teams'      => TeamController::class,
            'abouts'     => AboutController::class,
            'portfolio'  => PortfolioController::class,
            'service'    => ServicesController::class,
            'projects'   => ProjectsController::class,
            'profile'    => ProfileController::class,
            // 'edit-profile'    => EditProfileController::class,
        ]);

    });

});

app/Models/Team.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Plank\Mediable\Mediable;


class Team extends Model
{
    use HasFactory;
    use Mediable;

    protected $table = 'teams';

    protected $fillable = [
        'fullname',
        'position',
        'image',
        'phone'
    ];

}

app/Http/Controllers/Admin/TeamController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\TeamWork\StoreTeamWork;
use App\Http\Requests\TeamWork\UpdateTeamWork;
use App\Models\Team;
use App\Repositories\Admin\TeamRepository;
use Illuminate\Http\Request;

class TeamController extends Controller
{
    protected $repo;

    public function __construct(TeamRepository $repo)
    {
        $this->repo = $repo;
    }

    public function index()
    {
        $teams = $this->repo->all();
        return view('admin.teams.index', compact('teams'));
    }

    public function create()
    {
        return view('admin.teams.create');
    }

    public function store(StoreTeamWork $request)
    {
        $this->repo->store($request->all());
        return redirect()->route('teams.index');
    }

    public function show($id)
    {
        $team = $this->repo->findById($id);
        return view('admin.teams.show', compact('team'));
    }

    public function edit($id)
    {
        $team = $this->repo->findById($id);
        return view('admin.teams.edit', compact('team'));
    }

    public function update(UpdateTeamWork $request, $id)
    {
        $this->repo->update($request->all(), $id);
        return redirect()->route('teams.index');
    }

    public function destroy($id)
    {
        Team::where('id', $id)->delete();
        return redirect()->route('teams.index')
                        ->with('success','Lesson deleted successfully');
    }
}

app/Http/Controllers/TeamController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Team;

class TeamController extends Controller
{
    public function team()
    {
        $teams = Team::orderByDesc('created_at')->paginate(20);
        return view('client.team.index', compact('teams'));
    }
}

resources/views/admin/teams/create.blade.php
@extends('admin.layouts.main')

@section('title', 'Маълумот қўшиш')
<link rel="stylesheet" href="{{ asset('/administrator/summernote/summernote-bs4.css') }}">

@section('content_header')
    <h4>Маълумот қўшиш</h4>
@stop

@section('content')

    @if (Session::has('success'))
        <div class="alert alert-success text-center">
            {{ Session::get('success') }}
        </div>
    @endif

    <form action="{{ route('teams.store') }}" method="post" enctype="multipart/form-data">
        @csrf()
        <div class="form-group">
            <label class="form-label">Ф.И.О</label>
            <input class="form-control @error('full_name') is-invalid @enderror" name="full_name">
            <span class="text-danger">{{ $errors->first('full_name') }}</span>
        </div>
        <div class="form-group">
            <label>Лавозим</label>
            <input class="form-control  @error('position') is-invalid @else is-valid @enderror" name="position">
            <span class="text-danger">{{ $errors->first('position') }}</span>
        </div>
        <div class="form-group">
            <label>Телефон рақам</label>

            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-phone"></i></span>
                </div>
                <input class="form-control  @error('phone') is-invalid @else is-valid @enderror" type="text" name="phone"
                    id="phone" data-inputmask='"mask": "(999) 99-999-99-99"' data-mask> <br>
            </div>
            <span class="text-danger">{{ $errors->first('phone') }}</span>
        </div>
        <div class="form-group">
            <label>Расм</label>
            <input class="form-control @error('image') is-invalid @else is-valid @enderror" type="file" name="image"">
                <span class=" text-danger">{{ $errors->first('image') }}</span>
        </div>
        <button type="submit" class="btn btn-primary btn-md float-right"><i class="fa fa-check"></i>
            {{ __('Маълумотни сақлаш') }}</button>
    </form>

@stop

@section('js')
    <script>
        $(document).ready(function() {

            $('.phone').inputmask('(999)-999-9999');

        });
    </script>
@stop

resources/views/admin/teams/edit.blade.php
@extends('admin.layouts.main')

@section('title', __('Янги қўшилган маълумотни таҳрирлаш'))
<link rel="stylesheet" href="{{ asset('/administrator/summernote/summernote-bs4.css')  }}">

@section('content_header')
    <h4>{{ __('Янги қўшилган маълумотни таҳрирлаш') }}</h4>
@stop

@section('content')

    <form action="{{ route('teams.update', $team[0]->id) }}" method="POST" enctype="multipart/form-data">
        @csrf()
        @method('PUT')
        <div class="form-group">
            <label>Ф.И.О</label>
            <input class="form-control @error('full_name') is-invalid @else is-valid @enderror" name="full_name" value="{{ $team[0]->fullname }}">
            <span class="text-danger">{{ $errors->first('full_name') }}</span>
        </div>
        <div class="form-group">
            <label>Лавозим</label>
            <input class="form-control @error('position') is-invalid @else is-valid @enderror" name="position" value="{{ $team[0]->position }}">
            <span class="text-danger">{{ $errors->first('position') }}</span>
        </div>
        <div class="form-group">
            <label>Телефон рақам</label>
            <input class="form-control @error('phone') is-invalid @else is-valid @enderror" name="phone" value="{{ $team[0]->phone }}">
        </div>
        <div class="form-group">
            <label>Расм</label>
            <input class="form-control @error('image') is-invalid @else is-valid @enderror" type="file" name="image" value="{{ $team[0]->image }}" id="image">
            <span class="text-danger">{{ $errors->first('image') }}</span> 
        </div>

        <button type="submit" class="btn btn-primary float-right"><i class="fa fa-check"></i>&nbsp;&nbsp;{{ __('Маълумотни сақлаш') }}</button>
    </form>
@stop
@section('js')
    <script src="{{ asset('/administrator/summernote/summernote-bs4.min.js')  }}"></script>
    <script>
        $(document).ready(function() {
            $('.summernote').summernote({
                height: 300,
            });
        });
    </script>
@stop

resources/views/admin/teams/index.blade.php
@extends('admin.layouts.main')

@section('title', 'Бизнинг жамоа')

@section('content_header')
    <h4>Бизнинг жамоа</h4>
@stop

@section('content')
    <div class="card card-outline card-info">
        <div class="card-header">
            <h3 class="card-title">
                <a href="{{ route('teams.create') }}" class="btn btn-primary btn-md float-right"><span
                        class="fas fa-fw fa-plus"></span>Аъзо қўшиш
                </a>
            </h3>
        </div>
        <div class="card-body pad">
            <div class="mb-3">
                <table cellpadding="0" cellspacing="0" id="example" class="table table-bordered table-striped table-condensed">
                    <thead>
                    <tr class="text-info">
                        <th>№</th>
                        <th>Расм</th>
                        <th>Ф.И.О</th>
                        <th>Телефон рақам</th>
                        <th>Лавозим</th>

                        <th class="actions">Амаллар</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 1;?>
                    @foreach($teams as $item)
                        <tr>
                            <td>{{ $i++ }}</td>
                            <td style="width: 120px;"><img src="{{ $item->image }}" alt="" width="80%" height="100"></td>
                            <td>{{ $item->fullname }} </td>
                            <td>{{ $item->phone }} </td>
                            <td>{{ $item->position }} </td>
                            <td>
                                <a href="{{ route('teams.edit', $item->id) }}" class="btn btn-info btn-sm">
                                    <span class="fas fa-fw fa-pencil-alt"></span>
                                </a>
                                <form action="{{ route('teams.destroy',  $item->id) }}" method="post"
                                    onsubmit="return confirm('Сиз ростдан ҳам ушбу маълумотни ўчиришни хохлайсизми ?')">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-sm btn-danger">
                                        <span class="fas fa-fw fa-trash-alt"></span>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    {{ $teams->links() }}
    </div>
@stop
@section('js')
    <script>
        $(document).ready(function () {
            $('#example').DataTable();
        });
    </script>
@stop

resources/views/admin/teams/show.blade.php
@extends('admin.layouts.main')

@section('title', 'Бизнинг жамоа')

@section('content_header')
    <h4>Бизнинг жамоа</h4>
@stop

@section('content')
    <div class="card card-outline card-info">
    </div>
@stop
@section('js')

@stop